---
language: php
os:
  - linux
sudo: false
php:
  - 7.2
  - 7.3
  - nightly
matrix:
  allow_failures:
    - php: nightly
services:
  - memcached
  - mysql
addons:
  apt:
    packages:
      - libgeoip-dev
install:
  - pear channel-update pear.php.net
  - pecl install geoip-1.1.1
  - pear install http2
before_script:
  - cp etc/config.sample.json etc/config.json
script:
  - bash -c 'set -e;for file in $(find ./src -type f -regex .*\.php -print); do
    php -e -l -f "$file"; done'
