<?php namespace CarlBennett\Tools\Templates\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\Tools\Models\User\Invite as InviteModel;
$auth_user = $this->getContext()->auth_user;
$date_accepted = $this->getContext()->date_accepted;
$date_invited = $this->getContext()->date_invited;
$date_revoked = $this->getContext()->date_revoked;
$email = $this->getContext()->email;
$error = $this->getContext()->error;
$feedback = $this->getContext()->feedback;
$id = $this->getContext()->id;
$invited_by = $this->getContext()->invited_by;
$invited_user = $this->getContext()->invited_user;
$invites_available = $this->getContext()->invites_available;
$invites_available_str = number_format($invites_available) . ' invite' . ($invites_available !== 1 ? 's' : '');
$invites_sent = $this->getContext()->invites_sent;
$invites_used = $this->getContext()->invites_used;
$invites_used_str = number_format($invites_used) . ' invite' . ($invites_used !== 1 ? 's' : '');
$password_confirm = $this->getContext()->password_confirm;
$password_desired = $this->getContext()->password_desired;
$record_updated = $this->getContext()->record_updated;
$return = $this->getContext()->return;
$title = 'User Invite';

switch ($error) {
  case null: $error_str = 'Null'; break;
  case InviteModel::ERROR_SUCCESS: $error_str = 'Success'; break;
  case InviteModel::ERROR_INTERNAL_ERROR: $error_str = 'Internal Error'; break;
  case InviteModel::ERROR_ID_MALFORMED: $error_str = 'Id malformed'; break;
  case InviteModel::ERROR_ID_NOT_FOUND: $error_str = 'Id not found'; break;
  default: $error_str = sprintf('Unknown (%s)', $error);
}

require('./header.inc.phtml'); ?>
<div class="container">
<?php if (isset($return)) { ?>
  <p>Redirecting to <a href="<?=$return?>"><?=filter_var($return, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a>...</p>
<?php } ?>
<?php if (!is_null($error)) { ?>
  <div class="alert alert-<?=($error === InviteModel::ERROR_SUCCESS ? 'success' : 'danger')?>"><?=$error_str?></div>
<?php } ?>
<?php if ($id) { require('./NYI.inc.phtml'); require('./footer.inc.phtml'); return; } ?>
<?php if (!$id && !$auth_user) { require('./LoginRequired.inc.phtml'); require('./footer.inc.phtml'); return; } ?>
<?php if ($auth_user) { ?>
  <div class="alert alert-info">You currently have <strong><?=$invites_available_str?></strong> available. You have used <strong><?=$invites_used_str?></strong>.</div>
<?php if ($invites_available > 0) { ?>
  <h2>Send Invitation</h2>
  <p>Use the form below to extend an email letter invitation to join this site to another user.</p>
  <form method="POST">
    <div class="my-1 mx-3">
      <label for="email" class="sr-only">Invite an email address:</label>
      <input class="form-control form-control-sm" style="width:auto;" type="email" name="email" id="email" placeholder="Invite an email address" value="<?=filter_var($email, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>" required<?=(isset($feedback[0]) && $feedback[0] == 'email' ? ' autofocus' : '')?>/>
<?php if (isset($feedback[0]) && $feedback[0] == 'email') { ?>
      <div class="text-danger"><?=$feedback[1]?></div>
<?php } ?>
    </div>
    <div class="my-1 mx-3">
      <input class="btn btn-sm btn-success" type="submit" value="Invite"/>
    </div>
  </form>
<?php } ?>
<?php if ($invites_used > 0) { ?>
  <h2 class="mt-2">Sent Invites</h2>
  <p>Below are the invites you have sent that count as your used invites.</p>
  <table class="table">
    <thead>
      <tr>
        <th>Date Invited</th>
        <th>Date Revoked</th>
        <th>Date Accepted</th>
        <th>Email Address</th>
        <th>Invited User</th>
      </tr>
    </thead>
    <tbody>
<?php foreach ($invites_sent as $id) { ?>
      <tr><td colspan="5"><?=$id?></td></tr>
<?php } ?>
    </tbody>
  </table>
<?php } ?>
<?php } ?>
</div>
<?php require("./footer.inc.phtml"); ?>
