<?php namespace CarlBennett\Tools\Templates\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\Tools\Models\User\Invite as InviteModel;
$active_user = $this->getContext()->active_user;
$date_accepted = $this->getContext()->date_accepted;
$date_invited = $this->getContext()->date_invited;
$date_revoked = $this->getContext()->date_revoked;
$email = $this->getContext()->email;
$error = $this->getContext()->error;
$feedback = $this->getContext()->feedback;
$id = $this->getContext()->id;
$invited_by = $this->getContext()->invited_by;
$invited_user = $this->getContext()->invited_user;
$invites_available = $this->getContext()->invites_available;
$invites_available_str = number_format($invites_available) . ' invite' . ($invites_available !== 1 ? 's' : '');
$invites_sent = $this->getContext()->invites_sent;
$invites_used = $this->getContext()->invites_used;
$invites_used_str = number_format($invites_used) . ' invite' . ($invites_used !== 1 ? 's' : '');
$password_confirm = $this->getContext()->password_confirm;
$password_desired = $this->getContext()->password_desired;
$record_updated = $this->getContext()->record_updated;
$return = $this->getContext()->return;
$title = 'User Invite';

$fmt = 'D, M j, Y g:i A T';
$tz = ($active_user ? $active_user->getTimezoneObject() : 'Etc/UTC');

switch ($error) {
  case null: $error_str = 'Null'; break;
  case InviteModel::ERROR_SUCCESS: $error_str = 'Success'; break;
  case InviteModel::ERROR_INTERNAL_ERROR: $error_str = 'Internal Error'; break;
  case InviteModel::ERROR_ID_MALFORMED: $error_str = 'Id malformed'; break;
  case InviteModel::ERROR_ID_NOT_FOUND: $error_str = 'Id not found'; break;
  default: $error_str = sprintf('Unknown (%s)', $error);
}

require('./header.inc.phtml'); ?>
<div class="container">
<?php if (isset($return)) { ?>
  <p>Redirecting to <a href="<?=$return?>"><?=filter_var($return, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a>...</p>
<?php } ?>
<?php if (!is_null($error)) { ?>
  <div class="alert alert-<?=($error === InviteModel::ERROR_SUCCESS ? 'success' : 'danger')?>"><?=$error_str?></div>
<?php } ?>
<?php if ($id) { require('./NYI.inc.phtml'); require('./footer.inc.phtml'); return; } ?>
<?php if (!$id && !$active_user) { require('./LoginRequired.inc.phtml'); require('./footer.inc.phtml'); return; } ?>
<?php if ($active_user) { ?>
  <div class="alert alert-info">You currently have <strong><?=$invites_available_str?></strong> available. You have used <strong><?=$invites_used_str?></strong>.</div>
<?php if ($invites_available > 0) { ?>
  <h2>Send Invitation</h2>
  <p>Use the form below to extend an email letter invitation to join this site.</p>
  <form method="POST" class="my-1 mx-3">
    <div class="form-row">
      <label for="email" class="sr-only">Invite an email address:</label>
      <input class="form-control form-control-sm m-1 bg-dark text-light border-success" style="width:auto;" type="email" name="email" id="email" placeholder="Invite an email address" value="<?=filter_var($email, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>" required<?=(isset($feedback[0]) && $feedback[0] == 'email' ? ' autofocus' : '')?>/>
<?php if (isset($feedback[0]) && $feedback[0] == 'email') { ?>
      <div class="text-danger"><?=$feedback[1]?></div>
<?php } ?>
      <input class="btn btn-sm btn-success m-1" type="submit" value="Invite"/>
    </div>
  </form>
  <div class="card card-info my-3">
    <div class="card-header"><strong>Terms and Conditions</strong></div>
    <div class="card-body">
      <p class="card-text">By inviting a User to this site, you agree to the following terms and conditions:</p>
      <p class="card-text"><strong>Terms:</strong></p>
      <p class="card-text"><ul>
        <li><strong>Invited User</strong> &ndash; the User that will be extended an email invitation letter, and thus gains the privilege of creating a User.</li>
        <li><strong>the Site</strong> &ndash; the Internet website at the Url: &lt;<a href="<?=Common::relativeUrlToAbsolute('/')?>"><?=Common::relativeUrlToAbsolute('/')?></a>&gt;.</li>
        <li><strong>User</strong> &ndash; the account that a person controls from their web browser, tied to a unique email address, used to authenticate on the Site.</li>
      </ul></p>
      <p class="card-text"><strong>Conditions:</strong></p>
      <p class="card-text"><ol>
        <li>The email address must be unique to a single User; multiple Users with the same email address are not allowed.</li>
        <li>The Invited User must not already have a User on the Site.</li>
        <li>The Invited User will not cause harm to the Site.</li>
        <li>The Invited User has reasonable interest in use of the Site.</li>
        <li>You have explained to the person that you are using their email address to invite them to the Site, and they have given you authorization to do so.</li>
      </ol></p>
      <p class="card-text">If you disagree with any of the above, then you are not authorized to extend an invite. Do not continue.</p>
    </div>
  </div>
<?php } ?>
<?php if ($invites_used > 0) { ?>
  <h2 class="mt-2">Sent Invites</h2>
  <p>Below are the invites you have sent that count as your used invites.</p>
  <table class="table table-striped" id="sent_invites_tbl">
    <thead>
      <tr>
        <th>Date Invited</th>
        <th>Date Accepted</th>
        <th>Date Revoked</th>
        <th>Invited User</th>
      </tr>
    </thead>
    <tbody>
<?php foreach ($invites_sent as $inv) {
        if (is_string($inv)) { ?>
      <tr><td colspan="5"><?=$inv->getId()?></td></tr>
<?php   } else {
          $inv_date_accepted = $inv->getDateAccepted();
          $inv_date_invited = $inv->getDateInvited();
          $inv_date_revoked = $inv->getDateRevoked();

          if ($inv_date_accepted) $inv_date_accepted->setTimezone($tz);
          if ($inv_date_invited) $inv_date_invited->setTimezone($tz);
          if ($inv_date_revoked) $inv_date_revoked->setTimezone($tz);

          $inv_id_str = $inv->getId();
          $inv_date_accepted_str = (!is_null($inv_date_accepted) ? $inv_date_accepted->format($fmt) : '<em>(not accepted)</em>');
          $inv_date_invited_str = (!is_null($inv_date_invited) ? $inv_date_invited->format($fmt) : '<em>(not invited)</em>');
          $inv_date_revoked_str = (!is_null($inv_date_revoked) ? $inv_date_revoked->format($fmt) : '<em>(not revoked)</em>');
          $inv_email_str = $inv->getEmail();

          $inv_date_accepted_class = (!is_null($inv_date_accepted) ? 'text-success' : 'text-secondary');
          $inv_date_revoked_class = (!is_null($inv_date_revoked) ? 'text-danger' : 'text-secondary');
?>
      <tr>
        <td><?=$inv_date_invited_str?></td>
        <td class="<?=$inv_date_accepted_class?>"><?=$inv_date_accepted_str?></td>
        <td class="<?=$inv_date_revoked_class?>"><?=$inv_date_revoked_str?></td>
        <td><?=$inv_email_str?></td>
      </tr>
<?php   }
      } ?>
    </tbody>
  </table>
<?php ob_start(); ?>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#sent_invites_tbl').DataTable({
        "columnDefs": [
          { responsivePriority: 2, type: "date", targets: 0 },
          { responsivePriority: 3, type: "date", targets: 1 },
          { responsivePriority: 3, type: "date", targets: 2 },
          { responsivePriority: 4, type: "html", targets: 3 },
          { responsivePriority: 1, type: "html", targets: 4 }
        ],
        "responsive": true
      });
    });
  </script>
<?php $_footer_script = ob_get_clean(); ?>
<?php } ?>
<?php } ?>
</div>
<?php require('./footer.inc.phtml'); ?>
