<?php namespace CarlBennett\Tools\Templates\User;
use \CarlBennett\MVC\Libraries\Common;
$title = 'Log in';
$return = (
  isset($_REQUEST) && isset($_REQUEST['return']) ? $_REQUEST['return'] : null
);
if (!empty($return) && substr($return, 0, 1) != '/') $return = null;
if (!empty($return)) $return = Common::relativeUrlToAbsolute($return);
$email = $this->getContext()->email;
$error = $this->getContext()->error;
require("./header.inc.phtml"); ?>
<div class="container">
  <div class="card mx-auto" style="width:18rem;">
    <div class="card-body">
      <h2 class="card-title text-center mb-4"><?=$title;?></h2>
      <form method="POST">
        <div class="form-group">
          <label class="sr-only" for="email">Email address</label>
          <input class="form-control" type="email" id="email" placeholder="Email address" value="<?=filter_var($email, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
        </div>
        <div class="form-group">
          <label class="sr-only" for="password">Password</label>
          <input class="form-control" type="password" id="password" placeholder="Password" value=""/>
        </div>
        <div class="form-group text-center">
<?php if (!empty($return)) { ?>
          <a class="btn btn-primary" href="<?=filter_var($return, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>">Back</a>
<?php } ?>
          <button class="btn btn-success" type="submit">Submit</button>
        </div>
      </form>
    </div>
<?php if ($error) { ?>
    <div class="card-footer bg-danger font-weight-bold text-center text-white">
      <?=$error?>
    </div>
<?php } ?>
  </div>
</div>
<?php require("./footer.inc.phtml"); ?>
