<?php namespace CarlBennett\Tools\Templates\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\Tools\Libraries\User;
use \CarlBennett\Tools\Models\User\Profile as ProfileModel;
use \DateTimeZone;

$model = $this->getContext();

$acl_invite_users = ($model->acl_invite_users ? ' checked' : '');
$acl_manage_users = ($model->acl_manage_users ? ' checked' : '');
$acl_pastebin_admin = ($model->acl_pastebin_admin ? ' checked' : '');
$acl_phpinfo = ($model->acl_phpinfo ? ' checked' : '');
$acl_plex_requests = ($model->acl_plex_requests ? ' checked' : '');
$acl_plex_users = ($model->acl_plex_users ? ' checked' : '');
$avatar = filter_var($model->avatar, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$date_added = $model->date_added;
$date_banned = $model->date_banned;
$date_disabled = $model->date_disabled;
$display_name = filter_var($model->display_name, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$error = $model->error;
$email = filter_var($model->email, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$internal_notes = filter_var($model->internal_notes, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$is_banned = ($model->is_banned ? ' checked' : '');
$is_disabled = ($model->is_disabled ? ' checked' : '');
$manage = $model->manage;
$record_updated = $model->record_updated;

$fmt = 'D, M j, Y g:i A T';
$tz = ($active_user ? $active_user->getTimezoneObject() : new DateTimeZone('Etc/UTC'));
$tzs = DateTimeZone::listIdentifiers();

if ($date_added) $date_added->setTimezone($tz);
if ($date_banned) $date_banned->setTimezone($tz);
if ($date_disabled) $date_disabled->setTimezone($tz);
if ($record_updated) $record_updated->setTimezone($tz);

$id_str = (!is_null($active_user) ? $active_user->getId() : '<em>&ndash;</em>');
$date_added_str = (!is_null($date_added) ? $date_added->format($fmt) : '<em>(not added)</em>');
$date_banned_str = (!is_null($date_banned) ? $date_banned->format($fmt) : '<em>(not banned)</em>');
$date_disabled_str = (!is_null($date_disabled) ? $date_disabled->format($fmt) : '<em>(not disabled)</em>');
$record_updated_str = (!is_null($record_updated) ? $record_updated->format($fmt) : '<em>&ndash;</em>');

$date_banned_class = (!is_null($date_banned) ? 'text-danger' : 'text-secondary');
$date_disabled_class = (!is_null($date_disabled) ? 'text-warning' : 'text-secondary');

switch ($error)
{
  case ProfileModel::ERROR_NONE: $error_str = 'None'; break;
  case ProfileModel::ERROR_INTERNAL: $error_str = 'Internal error'; break;
  case ProfileModel::ERROR_EMAIL_INVALID: $error_str = 'Invalid email address'; break;
  case ProfileModel::ERROR_EMAIL_LENGTH: $error_str = 'Invalid email address length'; break;
  case ProfileModel::ERROR_DISPLAY_NAME_LENGTH: $error_str = 'Invalid display name length'; break;
  case ProfileModel::ERROR_INTERNAL_NOTES_LENGTH: $error_str = 'Invalid internal notes length'; break;
  case ProfileModel::ERROR_TIMEZONE_INVALID: $error_str = 'Invalid tomezone'; break;
  case ProfileModel::ERROR_TIMEZONE_LENGTH: $error_str = 'Invalid timezone string length'; break;
  default: $error_str = sprintf('Unknown (%d)', $error);
}

?>
<div class="container">
  <form method="POST">
<?php if ($error !== ProfileModel::ERROR_NONE) { ?>
    <div class="row">
      <div class="col-lg-12">
        <div class="alert alert-danger">
          <?=$error_str?>
        </div>
      </div>
    </div>
<?php } ?>
    <div class="row">
      <div class="col-md-1">
        <!-- Avatar -->

        <div class="text-center">
          <label class="font-weight-bold m-1">Gravatar</label>
          <img class="border border-primary p-1 rounded-lg" style="max-width:96px;" src="<?=$avatar?>"/>
        </div>

      </div>
      <div class="col-lg-6">
        <!-- Display name, Email address, Timezone, Options, Access Control -->

        <table class="table table-borderless">
          <thead></thead><tbody>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="display_name">Display name</label></th>
              <td><input class="form-control form-control-sm" type="text" id="display_name" name="display_name" placeholder="Enter the display name here" value="<?=$display_name?>"/></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="email">Email address</label></th>
              <td><input class="form-control form-control-sm" type="email" id="email" name="email" placeholder="Enter the email address here" value="<?=$email?>"/></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="timezone">Timezone</label></th>
              <td>
                <select class="custom-select custom-select-sm" id="timezone" name="timezone">
                  <option value=""<?=(!$tz ? ' selected' : '')?>>&ndash;</option>
<?php foreach ($tzs as $tzstr) { $tzstrf = filter_var($tzstr, FILTER_SANITIZE_FULL_SPECIAL_CHARS); ?>
                  <option value="<?=$tzstrf?>"<?=($tzstr == $tz->getName() ? ' selected' : '')?>><?=$tzstrf?></option>
<?php } ?>
                </select>
              </td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0">Options</label></th>
              <td>
<?php if ($manage) { ?>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="banned" id="is_banned" value="1"<?=$is_banned?>>
                  <label class="custom-control-label text-danger" for="is_banned">
                    Banned<br/><span style="font-size:smaller;" class="text-muted">Suspends the account permanently; user cannot resume account</span>
                  </label>
                </div>
<?php } ?>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="disabled" id="is_disabled" value="1"<?=$is_disabled?>>
                  <label class="custom-control-label text-warning" for="is_disabled">
                    Disabled<br/><span style="font-size:smaller;" class="text-muted">Suspends the account temporarily<?=($manage ? '; user may resume account' : '')?></span>
                  </label>
                </div>

                <p class="alert alert-primary text-muted text-center" style="font-size:smaller;">Active login sessions will end if banned or disabled.</p>
              </td>
            </tr>
<?php if ($manage) { ?>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0">Access Control</label></th>
              <td>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="acl_invite_users" id="acl_invite_users" value="1"<?=$acl_invite_users?>> <label class="custom-control-label" for="acl_invite_users">Invite Users<br/>
                  <span style="font-size:smaller;" class="text-muted">Able to invite users to the site</span></label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="acl_manage_users" id="acl_manage_users" value="1"<?=$acl_manage_users?>> <label class="custom-control-label" for="acl_manage_users">Manage Users<br/>
                  <span style="font-size:smaller;" class="text-muted">Manage site users</span></label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="acl_pastebin_admin" id="acl_pastebin_admin" value="1"<?=$acl_pastebin_admin?>> <label class="custom-control-label" for="acl_pastebin_admin">Pastebin Admin<br/>
                  <span style="font-size:smaller;" class="text-muted">Manage pastebin data</span></label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="acl_phpinfo" id="acl_phpinfo" value="1"<?=$acl_phpinfo?>> <label class="custom-control-label" for="acl_phpinfo">Php Info<br/>
                  <span style="font-size:smaller;" class="text-muted">Able to view <code>phpinfo()</code></span></label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="acl_plex_requests" id="acl_plex_requests" value="1"<?=$acl_plex_requests?>> <label class="custom-control-label" for="acl_plex_requests">Plex Requests<br/>
                  <span style="font-size:smaller;" class="text-muted">Manage Plex media requests</span></label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="acl_plex_users" id="acl_plex_users" value="1"<?=$acl_plex_users?>> <label class="custom-control-label" for="acl_plex_users">Plex Users<br/>
                  <span style="font-size:smaller;" class="text-muted">Manage Plex user data</span></label>
                </div>
              </td>
            </tr>
<?php } ?>
          </tbody>
        </table>

      </div>
      <div class="col-lg-5">
        <!-- Uuid, Timestamps -->

        <table class="table table-borderless">
          <thead></thead><tbody>
            <tr>
              <th scope="row" class="align-middle text-right">Uuid</th>
              <td><code><?=$id_str?></code></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right text-success">Date added</th>
              <td class="text-success"><?=$date_added_str?></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right <?=$date_banned_class?>">Date banned</th>
              <td class="<?=$date_banned_class?>"><?=$date_banned_str?></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right <?=$date_disabled_class?>">Date disabled</th>
              <td class="<?=$date_disabled_class?>"><?=$date_disabled_str?></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right text-info">Record last updated</th>
              <td class="text-info"><?=$record_updated_str?></td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
<?php if ($manage) { ?>
    <div class="row">
      <div class="col">
        <!-- Internal notes -->

        <label class="font-weight-bold" for="internal_notes">Internal notes</label><br/>
        <textarea class="form-control form-control-sm" style="min-height:90px;" id="internal_notes" name="internal_notes" placeholder="Enter internal notes here"><?=$internal_notes?></textarea>

      </div>
    </div>
<?php } ?>
    <hr/>
    <div class="row">
      <div class="col">
        <div class="text-center">
          <a class="btn btn-primary mr-2" href="javascript:history.go(-1);">Back</a>
          <input class="btn btn-success" type="submit" value="Save"/>
        </div>
      </div>
    </div>
  </form>
</div>
