<?php namespace CarlBennett\Tools\Templates; use \CarlBennett\MVC\Libraries\Common; ?>
</main>

<footer class="footer mt-auto py-3">
  <div class="container text-center">
    <span class="small text-muted">
      Copyright &copy; <?=date('Y')?> <a href="https://carlbennett.me/">Carl Bennett</a>, All Rights Reserved. <a href="<?=Common::relativeUrlToAbsolute('/privacy')?>">Privacy Notice</a>
    </span>
  </div>
</footer>

<script src="/a/jquery-3.4.1.slim.min.js" type="text/javascript" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"><![CDATA[]]></script>
<script src="/a/popper-1.16.0.min.js" type="text/javascript" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"><![CDATA[]]></script>
<script src="/a/bootstrap-4.4.1.min.js" type="text/javascript" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"><![CDATA[]]></script>
<script src="/a/datatables.min.js" type="text/javascript" crossorigin="anonymous" charset="utf8"><![CDATA[]]></script>
<script src="/a/moment-2.29.2.min.js" type="text/javascript" crossorigin="anonymous" charset="utf8"><![CDATA[]]></script>
<?php if (!empty($_footer_script)) { echo $_footer_script; } ?>
</body></html>
