<?php namespace CarlBennett\Tools\Templates; $title = "Tool Index"; ?>
<?php require("./header.inc.phtml"); ?>
<div class="container">
  <h1><?=$title;?></h1>
  <div class="row">
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr><th scope="col">Pattern</th><th scope="col">Controller</th></tr>
      </thead>
      <tbody>
<?php foreach ($this->getContext()->routes as $route => $controller) { ?>
        <tr><td><?=$route?></td><td><?=$controller[0]?></td></tr>
<?php } ?>
      </tbody>
    </table>
  </div>
</div>
<?php require("./footer.inc.phtml"); ?>
