<?php namespace CarlBennett\Tools\Templates; $title = "Tool Index"; ?>
<?php require("./header.inc.phtml"); ?>
<div class="container">
  <h1><?=$title;?></h1>
  <div class="row">
    <table class="table table-bordered table-hover table-sm" id="controllers">
      <thead class="thead-light">
        <tr><th scope="col">Pattern</th><th scope="col">Controller</th><th scope="col">View</th></tr>
      </thead>
      <tbody>
<?php foreach ($this->getContext()->routes as $route => $args) {
        $controller = $args[0];
        $view = $args[1];
?>
        <tr><td><?=$route?></td><td><?=$controller?></td><td><?=$view?></td></tr>
<?php } ?>
      </tbody>
    </table>
  </div>
</div>
<?php require("./footer.inc.phtml"); ?>
