<?php namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
?>
<div class="alert alert-danger clearfix">
  You must be <strong>logged in</strong> and have
  <strong>sufficient permission</strong> to access this resource.
</div>
<div class="text-center">
  <a class="btn btn-primary" href="javascript:history.go(-1);">Back</a>
  <a class="btn btn-success" href="<?=Common::relativeUrlToAbsolute(
    '/user/login?return=' . rawurlencode(getenv('REQUEST_URI')))?>">Log in</a>
</div>
