<?php /* vim: set colorcolumn=0: */
namespace CarlBennett\Tools\Templates;
$title = 'Privacy Notice';
$active_user = $this->getContext()->active_user;
$data_location = $this->getContext()->data_location;
$email_domain = $this->getContext()->email_domain;
$web_domain = $this->getContext()->web_domain;
$org = $this->getContext()->org;
require('./header.inc.phtml'); ?>
<div class="container">

  <nav id="table-of-contents">
    <h2>Table of Contents</h2>
    <ul>
      <li><a href="#information-we-collect">Information We Collect</a></li>
      <li><a href="#legal-basis">Legal Basis for Processing Personal Data</a></li>
      <li><a href="#how-we-use">How We Use Your Information</a></li>
      <li><a href="#disclosure">Disclosure of Your Information</a></li>
      <li><a href="#data-subject-rights">Data Subject Rights</a></li>
      <li><a href="#cookies">Cookies</a></li>
      <li><a href="#security">Security</a></li>
      <li><a href="#changes">Changes to This Privacy Notice</a></li>
      <li><a href="#contact-us">Contact Us</a></li>
    </ul>
  </nav>

  <h1>Privacy Notice</h1>
  <p>This Privacy Notice explains how we ("<?=filter_var($org, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>") collect, use, disclose, and safeguard your personal information when you visit our website <code><?=filter_var($web_domain, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code> ("Website").</p>

  <h2 id="information-we-collect">Information We Collect</h2>
  <p>We may collect personal information that you voluntarily provide to us when you interact with the Website. This may include, but is not limited to, your name, email address, IP address, and any other information you choose to provide.</p>

  <h2 id="legal-basis">Legal Basis for Processing Personal Data</h2>
  <p>We will only process your personal data when we have a legal basis for doing so. Common legal bases include the performance of a contract, compliance with a legal obligation, protection of vital interests, consent, the performance of a task carried out in the public interest or the exercise of official authority, and legitimate interests pursued by the data controller or a third party.</p>
  <p>The processing of personal data on this Website is based on the legal framework applicable in the <?=filter_var($data_location, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>. As the Website is located in the <?=filter_var($data_location, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>, data processing activities are subject to relevant <?=filter_var($data_location, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?> laws and regulations.</p>

  <h2 id="how-we-use">How We Use Your Information</h2>
  <p>We may use the information we collect for various purposes, including:</p>
  <ul>
    <li>To personalize your experience on the Website.</li>
    <li>To improve our Website based on your feedback.</li>
    <li>To send periodic emails regarding our products and services.</li>
    <li>To respond to your inquiries or requests.</li>
  </ul>

  <h2 id="disclosure">Disclosure of Your Information</h2>
  <p>We do not sell, trade, or otherwise transfer your personal information to outside parties. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, as long as those parties agree to keep this information confidential.</p>

  <h2 id="data-subject-rights">Data Subject Rights</h2>
  <p>Under the GDPR, you have the right to access, rectify, or erase your personal data, as well as the right to restrict or object to certain processing activities. You also have the right to data portability. To exercise these rights, please feel free to contact us. You can email any mailbox at <code><?=filter_var($email_domain, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code>, and it will be directed to the correct person.</p>

  <h2 id="cookies">Cookies</h2>
  <p>Our Website may use cookies to enhance your experience. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information.</p>
  <p>If you prefer, you can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies via your browser settings. However, some features of our Website may not function properly without the aid of cookies.</p>

  <h2 id="security">Security</h2>
  <p>We employ the following measures to secure your data:</p>
  <ol>
    <li><strong>Relational Database:</strong> Data is stored in a relational database.</li>
    <li><strong>Redundancy:</strong> Data redundancy safeguards against hardware failure.</li>
    <li><strong>Access Control:</strong> Data access is restricted to authorized personnel.</li>
    <li><strong>Firewall Protection:</strong> A firewall separates the database from the Internet, preventing unauthorized access.</li>
    <li><strong>Network Isolation:</strong> VLANs isolate the network, preventing unknown traffic from reaching the data.</li>
    <li><strong>Regular Backups:</strong> Scheduled backups are automated to ensure data backup at regular intervals.</li>
    <li><strong>Offsite Redundant Storage:</strong> Database backups are securely stored in a nearby redundant location.</li>
  </ol>

  <h2 id="changes">Changes to This Privacy Notice</h2>
  <p>We may update this Privacy Notice from time to time by posting a new version on this page. You are advised to review this Privacy Notice periodically for any changes.</p>

  <h2 id="contact-us">Contact Us</h2>
  <p>If you have any questions or concerns about this Privacy Notice or our data practices, please feel free to contact us. You can email any mailbox at <code><?=filter_var($email_domain, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code>, and it will be directed to the correct person.</p>

</div>
<?php require('./footer.inc.phtml'); ?>
