<?php namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
$title = 'Remote Address';
$geoip = $this->getContext()->geoip_info;
$ip = $this->getContext()->ip_address;
$ua = $this->getContext()->user_agent;
$ua_max = 100;
require("./header.inc.phtml"); ?>
<div class="container">
  <h1>Remote Address</h1>
  <div class="align-middle mb-2">
    <strong>Alternative formats:</strong>
    <a class="btn btn-sm btn-primary" href="<?=Common::relativeUrlToAbsolute('/remoteaddress.json')?>">Json</a>
    <a class="btn btn-sm btn-primary" href="<?=Common::relativeUrlToAbsolute('/remoteaddress.txt')?>">Plaintext</a>
  </div>
  <table class="table table-bordered table-sm">
    <thead></thead>
    <tbody>
      <tr><th scope="row" class="bg-primary border-dark text-right">IP Address</th><td class="border-primary text-left"><code><?=filter_var($ip, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></td></tr>
<?php if ($ua && strlen($ua) <= $ua_max) { ?>
      <tr><th scope="row" class="bg-primary border-dark text-right">User Agent</th><td class="border-primary text-left"><code><?=filter_var($ua, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></td></tr>
<?php } else if ($ua && strlen($ua) > $ua_max) { ?>
      <tr><th scope="row" class="bg-primary border-dark text-right">User Agent</th><td class="border-primary text-left"><code><?=filter_var(substr($ua, 0, $ua_max), FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code>&hellip;</td></tr>
<?php } else { ?>
      <tr><th scope="row" class="bg-primary border-dark text-right">User Agent</th><td class="border-primary text-left"><em>not available</em></td></tr>
<?php } ?>
    </tbody>
  </table>
</div>
<?php require("./footer.inc.phtml"); ?>
