<?php /* vim: set colorcolumn=0: */
namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\Tools\Libraries\User;
use \CarlBennett\Tools\Libraries\User\Acl;
$title = 'Tool Overview';
$active_user = $this->getContext()->active_user;
$active_user_acl = ($active_user ? $active_user->getAclObject() : null);
require("./header.inc.phtml"); ?>
<div class="container">
  <h3>Select a Tool</h3>
  <p>The following are the set of tools available.</p>
  <table class="table table-striped">
    <thead><tr><th>Tool</th><th>Description</th></tr></thead>
    <tbody>
<?php if ($active_user) { ?>
      <tr>
        <td><a title="Edit Profile" href="<?=$active_user->getUrl()?>">📝 Edit Profile</a></td>
        <td>Edit your account profile.</td>
      </tr>
<?php } ?>
      <tr>
        <td><a title="Gandalf Sax Guy for 10 hours" href="<?=Common::relativeUrlToAbsolute('/gandalf')?>">🎶 Gandalf </a></td>
        <td>Gandalf Sax Guy for 10 hours.</td>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_USERS_INVITE)) { ?>
      <tr>
        <td><a title="Invite User" href="<?=Common::relativeUrlToAbsolute('/user/invite')?>">👤 Invite User</a></td>
        <td>Invite user to Carl's Toolbox.</td>
      </tr>
<?php } ?>
      <tr>
<?php if ($active_user) { ?>
        <td><a title="Log out" href="<?=Common::relativeUrlToAbsolute('/user/logout?return=/tools')?>">🔑 Log Out</a></td>
        <td>Log out from your account.</td>
<?php } else { ?>
        <td><a title="Log in" href="<?=Common::relativeUrlToAbsolute('/user/login?return=/tools')?>">🔑 Log In</a></td>
        <td>Log in to your account.</td>
<?php } ?>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_USERS_MANAGE)) { ?>
      <tr>
        <td><a title="Manage Users" href="<?=Common::relativeUrlToAbsolute('/users')?>">👥 Manage Users</a></td>
        <td>Manage users for Carl's Toolbox.</td>
      </tr>
<?php } ?>
      <tr>
        <td><a title="Pastebin" href="<?=Common::relativeUrlToAbsolute('/paste')?>">📝 Pastebin</a></td>
        <td>A quick place to paste stuff.</td>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_PHPINFO)) { ?>
      <tr>
        <td><a title="Php Info" href="<?=Common::relativeUrlToAbsolute('/phpinfo')?>">ℹ Php Info</a></td>
        <td>Prints PHP runtime information.</td>
      </tr>
<?php } ?>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_PLEX_USERS)) { ?>
      <tr>
        <td><a title="Plex Users" href="<?=Common::relativeUrlToAbsolute('/plex/users')?>">👥 Plex Users</a></td>
        <td>Manage users for Carl's Plex.</td>
      </tr>
<?php } ?>
      <tr>
        <td><a title="Privacy Notice" href="<?=Common::relativeUrlToAbsolute('/privacy')?>">🔏 Privacy Notice</a></td>
        <td>The site's privacy notice and your rights.</td>
      </tr>
      <tr>
        <td><a title="Remote Address" href="<?=Common::relativeUrlToAbsolute('/remoteaddress')?>">🏠 Remote Address</a></td>
        <td>Show your IP address info.</td>
      </tr>
      <tr>
        <td><a title="Url Encode &amp; Decode" href="<?=Common::relativeUrlToAbsolute('/urlencodedecode')?>">⚙ Url Encode &amp; Decode</a></td>
        <td>Encode and decode url strings.</td>
      </tr>
    </tbody>
  </table>
<?php if (!$active_user) { ?>
  <p>Additional tools are gated and require authentication, please <a title="Log in" href="<?=Common::relativeUrlToAbsolute('/user/login?return=/tools')?>">Log in <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-box-arrow-in-up-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M6.364 13.5a.5.5 0 0 0 .5.5H13.5a1.5 1.5 0 0 0 1.5-1.5v-10A1.5 1.5 0 0 0 13.5 1h-10A1.5 1.5 0 0 0 2 2.5v6.636a.5.5 0 1 0 1 0V2.5a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v10a.5.5 0 0 1-.5.5H6.864a.5.5 0 0 0-.5.5z"/>
                <path fill-rule="evenodd" d="M11 5.5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793l-8.147 8.146a.5.5 0 0 0 .708.708L10 6.707V10.5a.5.5 0 0 0 1 0v-5z"/>
              </svg></a> for more tools.</p>
<?php } else { ?>
<?php } ?>
</div>
<?php require("./footer.inc.phtml"); ?>
