<?php /* vim: set colorcolumn=0: */
namespace CarlBennett\Tools\Templates;
use \CarlBennett\Tools\Libraries\Core\UrlFormatter;
use \CarlBennett\Tools\Libraries\User\Acl;
$title = 'Tool Overview';
$active_user = $this->getContext()->active_user;
$active_user_acl = ($active_user ? $active_user->getAclObject() : null);
require("./header.inc.phtml"); ?>
<div class="container">
  <h3>Select a Tool</h3>
  <p>The following are the set of tools available.</p>
  <table class="table table-striped">
    <thead><tr><th>Tool</th><th>Description</th></tr></thead>
    <tbody>
<?php if ($active_user) { ?>
      <tr>
        <td><a title="Edit Profile" href="<?=$active_user->getUrl()?>">📝 Edit Profile</a></td>
        <td>Edit your account profile.</td>
      </tr>
<?php } ?>
      <tr>
        <td><a title="Gandalf Sax Guy for 10 hours" href="<?=UrlFormatter::format('/gandalf')?>">🎶 Gandalf </a></td>
        <td>Gandalf Sax Guy for 10 hours.</td>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_USERS_INVITE)) { ?>
      <tr>
        <td><a title="Invite User" href="<?=UrlFormatter::format('/user/invite')?>">👤 Invite User</a></td>
        <td>Invite user to Carl's Toolbox.</td>
      </tr>
<?php } ?>
      <tr>
<?php if ($active_user) { ?>
        <td><a title="Log out" href="<?=UrlFormatter::format('/user/logout?return=/tools')?>">🔑 Log Out</a></td>
        <td>Log out from your account.</td>
<?php } else { ?>
        <td><a title="Log in" href="<?=UrlFormatter::format('/user/login?return=/tools')?>">🔑 Log In</a></td>
        <td>Log in to your account.</td>
<?php } ?>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_USERS_MANAGE)) { ?>
      <tr>
        <td><a title="Manage Users" href="<?=UrlFormatter::format('/users')?>">👥 Manage Users</a></td>
        <td>Manage users for Carl's Toolbox.</td>
      </tr>
<?php } ?>
      <tr>
        <td><a title="Minecraft /setblock Macro" href="<?=UrlFormatter::format('/minecraft/setblock-macro')?>">⛏ Minecraft /setblock Macro</a></td>
        <td>Generates setblock commands to fill a region for command-block macros.</td>
      </tr>
      <tr>
        <td><a title="Pastebin" href="<?=UrlFormatter::format('/paste')?>">📝 Pastebin</a></td>
        <td>A quick place to paste stuff.</td>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_PHPINFO)) { ?>
      <tr>
        <td><a title="Php Info" href="<?=UrlFormatter::format('/phpinfo')?>">🐘 Php Info</a></td>
        <td>Prints PHP runtime information.</td>
      </tr>
<?php } ?>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_PLEX_USERS)) { ?>
      <tr>
        <td><a title="Plex Users" href="<?=UrlFormatter::format('/plex/users')?>">👥 Plex Users</a></td>
        <td>Manage users for Carl's Plex.</td>
      </tr>
<?php } ?>
      <tr>
        <td><a title="Privacy Notice" href="<?=UrlFormatter::format('/privacy')?>">🔏 Privacy Notice</a></td>
        <td>The site's privacy notice and your rights.</td>
      </tr>
      <tr>
        <td><a title="Remote Address" href="<?=UrlFormatter::format('/remoteaddress')?>">🏠 Remote Address</a></td>
        <td>Show your IP address info.</td>
      </tr>
      <tr>
        <td><a title="Url Encode &amp; Decode" href="<?=UrlFormatter::format('/urlencodedecode')?>">⚙ Url Encode &amp; Decode</a></td>
        <td>Encode and decode url strings.</td>
      </tr>
<?php if ($active_user_acl && $active_user_acl->getAcl(Acl::ACL_WHOIS_SERVICE)) { ?>
      <tr>
        <td><a title="Whois Service" href="<?=UrlFormatter::format('/whois')?>">🔍 Whois Service</a></td>
        <td>Looks up domain name and ASN information on the Internet.</td>
      </tr>
<?php } ?>
    </tbody>
  </table>
<?php if (!$active_user) { ?>
  <div class="alert alert-secondary"><p class="mb-0">💁🏻‍♂️ Additional tools are gated and require authentication. <a class="btn btn-sm btn-outline-success" title="Log in" href="<?=UrlFormatter::format('/user/login?return=/tools')?>">Log in</a></p></div>
<?php } else { ?>
<?php } ?>
</div>
<?php require("./footer.inc.phtml"); ?>
