<?php namespace CarlBennett\Tools\Templates;
$title = 'Url Encode & Decode';
$decode = $this->getContext()->decode;
$input = $this->getContext()->input;
$output = $this->getContext()->output;
require('./header.inc.phtml'); ?>
<div class="container">
  <h1>Url Encode &amp; Decode</h1>
  <p>This tool is a user interface to the PHP <code><a href="https://www.php.net/manual/function.rawurlencode.php">rawurlencode()</a></code> and <code><a href="https://www.php.net/manual/function.rawurldecode.php">rawurldecode()</a></code> functions.</p>
  <form method="POST">
    <div class="row">
      <div class="col">
        <h2>Input</h2>
        <div class="m-3">
          <div class="custom-control custom-switch m-2">
            <input class="custom-control-input" type="checkbox" name="decode" id="decode" value="1"<?=$decode ? ' checked' : ''?>> <label class="custom-control-label" for="decode">Decode</label>
          </div>
          <textarea name="input" id="input" class="form-control bg-dark text-light"><?=filter_var($input, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></textarea>
        </div>
      </div>
    </div>
<?php if (!empty($output)) { ?>
    <div class="row">
      <div class="col">
        <h2>Output</h2>
        <div class="m-3">
          <textarea id="output" class="form-control bg-dark text-light"><?=filter_var($output, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></textarea>
        </div>
      </div>
    </div>
<?php } ?>
    <div class="row">
      <div class="col">
        <input type="submit" class="btn btn-success" value="Submit"/>
      </div>
    </div>
  </form>
</div>
<?php require('./footer.inc.phtml'); ?>
