<?php
namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
$title = 'Whois';
$query = $this->getContext()->query;
$query_result = $this->getContext()->query_result;
require("./header.inc.phtml");
?>
<div class="container">
  <h1><?=$title;?></h1>
  <form method="GET" action="<?=Common::relativeUrlToAbsolute('/whois')?>">
    <div class="form-group">
      <input type="text" class="form-control" id="query" name="q" placeholder="Search query" value="<?=filter_var($query, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </form>
<?php if (!empty($query_result)) { ?>
  <div class="form-group">
    <textarea rows="20" class="form-control text-monospace" readonly><?=filter_var($query_result, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></textarea>
  </div>
<?php } ?>
</div>
<?php require("./footer.inc.phtml"); ?>
