<?php
namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
$title = 'Whois';
$query = $this->getContext()->query;
$query_result = $this->getContext()->query_result;
$recursive = $this->getContext()->recursive;
require("./header.inc.phtml");
?>
<div class="container mb-4">
  <h1><?=$title;?></h1>
  <form method="GET" action="<?=Common::relativeUrlToAbsolute('/whois')?>">
    <div class="form-group">
      <input type="text" class="form-control mb-2" id="query" name="q" placeholder="Search query" value="<?=filter_var($query, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" value="0" id="recursiveOff" name="r"<?=(!$recursive ? ' checked' : '')?>/>
        <label class="form-check-label" for="recursiveOff">Recursive Off</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" value="1" id="recursiveOn" name="r"<?=($recursive ? ' checked' : '')?>/>
        <label class="form-check-label" for="recursiveOn">Recursive On</label>
      </div>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </form>
<?php if (!empty($query_result)) { ?>
  <code><?=nl2br(filter_var($query_result, FILTER_SANITIZE_FULL_SPECIAL_CHARS))?></code>
<?php } ?>
</div>
<?php require("./footer.inc.phtml"); ?>
