<?php namespace CarlBennett\Tools\Templates; $title = "Create BNETDocs Password"; ?>
<?php require("./header.inc.phtml"); ?>
<form method="POST" action="?">
<label for="password">Password:</label><br/>
<input type="password" name="password" id="password" value=""
  autofocus="autofocus" tabindex="1"/><br/>
<input type="submit" value="Create"/>
</form>
<p>
<?php if (!empty($this->getContext()->seed)) { ?>
<strong>Seed:</strong> <?=$this->getContext()->seed?><br/>
<?php } ?>
<?php if (!empty($this->getContext()->hash)) { ?>
<strong>Hash:</strong> <?=$this->getContext()->hash?><br/>
<?php } ?>
</p>
<?php require("./footer.inc.phtml"); ?>
