<?php
namespace CarlBennett\Tools\Templates;
$title = 'Plex Requests';
$active_user = $this->getContext()->active_user;
require('./header.inc.phtml');
?>
<div class="container">
  <h1><?=$title;?></h1>
<?php if (!$active_user) {
  require('./LoginRequired.inc.phtml');
  echo '</div>';
  require('./footer.inc.phtml');
  return;
} ?>

  <div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Request filter toolbar">
    <div class="btn-group mr-2" role="group" aria-label="Request filters">
      <button type="button" class="btn btn-secondary">Open</button>
      <button type="button" class="btn btn-secondary">Ongoing</button>
      <button type="button" class="btn btn-secondary">Closed</button>
    </div>
    <div class="btn-group" role="group" aria-label="Start a request">
      <button type="button" class="btn btn-success">New</button>
    </div>
  </div>
</div>
<?php require('./footer.inc.phtml');
