<?php
namespace CarlBennett\Tools\Templates;
$title = 'Plex Requests';
$active_user = $this->getContext()->active_user;
require('./header.inc.phtml');
?>
<div class="container">
  <h1><?=$title;?></h1>
<?php if (!$active_user) {
  require('./LoginRequired.inc.phtml');
  echo '</div>';
  require('./footer.inc.phtml');
  return;
} ?>
  <p class="text-center text-danger">Mock UI</p>

  <div class="btn-toolbar justify-content-center mb-4" role="toolbar" aria-label="Request filter toolbar">
    <div class="btn-group mr-2" role="group" aria-label="Request filters">
      <button type="button" class="btn btn-secondary">Open</button>
      <button type="button" class="btn btn-secondary">Ongoing</button>
      <button type="button" class="btn btn-secondary">Closed</button>
    </div>
    <div class="btn-group" role="group" aria-label="Start a request">
      <button type="button" class="btn btn-success">New</button>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <img class="card-img float-left mr-3" style="max-width:150px;" src="https://m.media-amazon.com/images/M/MV5BZTFkZjYxNWItZmE2MC00MGE4LWIxYTgtZmIzOWM1YmI2YWEzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg" alt="Greyhound (2020) Poster"/>
          <h5 class="card-title">Greyhound (2020) <span class="badge badge-warning">Open</span></h5>
          <p class="card-text">Several months after the U.S. entry into World War II, an inexperienced U.S. Navy commander must lead an Allied convoy being stalked by a German submarine wolf pack.</p>
          <a href="#" class="btn btn-sm btn-success" title="Approve">✔</a>
          <a href="#" class="btn btn-sm btn-danger" title="Decline">❌</a>
          <a href="https://www.imdb.com/title/tt6048922/" title="IMDb"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/IMDb_logo.svg/56px-IMDb_logo.svg.png" alt="IMDb"/></a>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <img class="card-img float-left mr-3" style="max-width:150px;" src="https://m.media-amazon.com/images/M/MV5BNjY5MzdiOGQtY2IwNC00Njg0LWIwNWEtNmJjMGRjNzJiMWU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg" alt="Robin&apos;s Wish (2020) Poster"/>
          <h5 class="card-title">Robin&apos;s Wish (2020) <span class="badge badge-warning">Open</span></h5>
          <p class="card-text">An intimate portrait of Robin Williams and his invulnerable spirit, Robin's Wish is the story of what really happened to one of the greatest entertainers of all time - and what his mind was fighting.</p>
          <a href="#" class="btn btn-sm btn-success" title="Approve">✔</a>
          <a href="#" class="btn btn-sm btn-danger" title="Decline">❌</a>
          <a href="https://www.imdb.com/title/tt12763474/" title="IMDb"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/IMDb_logo.svg/56px-IMDb_logo.svg.png" alt="IMDb"/></a>
        </div>
      </div>
    </div>
  </div>
</div>
<?php require('./footer.inc.phtml');
