<?php
namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\Tools\Libraries\Plex\User as PlexUser;
$title = 'Plex Users';
require('./header.inc.phtml'); ?>
<div class="container">
<?php if ($this->getContext()->users === false) { ?>
  <h1><?=$title;?></h1>
  <?php require('./LoginRequired.inc.phtml'); ?>
<?php } else { ?>
  <div class="float-right"><a class="btn btn-lg btn-success" href="<?=Common::relativeUrlToAbsolute('/plex/users/add')?>">Add User</a></div>
  <h1><?=$title;?></h1>
  <table class="table table-hover table-striped">
    <thead class="thead-dark"><tr>
      <th scope="col">Username &amp; Email</th>
      <th scope="col">Added</th>
      <th scope="col"></th>
    </tr></thead>
    <tbody>
<?php foreach ($this->getContext()->users as $user) {
        $id = filter_var($user->getId(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $username = filter_var($user->getUsername(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $email = filter_var($user->getEmail(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $removed = (!is_null($user->getDateRemoved()) ? ' <span class="badge badge-danger">Removed</span> ' : '');
        $risk = $user->getRisk();
        if (empty($username) && !empty($email)) {
          $name = $email;
        } else if (!empty($username) && empty($email)) {
          $name = $username;
        } else {
          $name = $username . '<br/><span class="text-secondary">' . $email . '</span>';
        }
        switch ($risk) {
          case PlexUser::RISK_UNASSESSED: $risk = array('danger', 'Unassessed'); break;
          case PlexUser::RISK_LOW: $risk = array('success', 'Low'); break;
          case PlexUser::RISK_MEDIUM: $risk = array('warning', 'Medium'); break;
          case PlexUser::RISK_HIGH: $risk = array('danger', 'High'); break;
          default: $risk = array('info', sprintf('Unknown (%d)', $risk));
        }
        if (empty($removed)) {
          $risk = sprintf(' <span class="badge badge-%s">%s Risk</span> ', $risk[0], $risk[1]);
        } else {
          $risk = '';
        }
        ?>
      <tr>
        <td><?=$name?></td>
        <td><time datetime="<?=$user->getDateAdded()->format(DATE_W3C)?>"><?=$user->getDateAdded()->format('D, M jS, Y')?></time></td>
        <td class="text-right"><?=$risk?><?=$removed?>
          <a class="btn btn-sm btn-primary" href="<?=Common::relativeUrlToAbsolute('/plex/users/edit?id=' . $id)?>">Edit</a>
        </td>
      </tr>
<?php } ?>
    </tbody>
  </table>
<?php } ?>
</div>
<?php require('./footer.inc.phtml'); ?>
