<?php
namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Gravatar;
use \CarlBennett\Tools\Libraries\Plex\User as PlexUser;
use \DateTimeZone;
$show_hidden = $this->getContext()->show_hidden;
$highlight_id = $this->getContext()->id;
$highlight_act = $this->getContext()->hl;
if (!empty($highlight_id)) {
  try {
    $highlight_user = new PlexUser($highlight_id);
  } catch (\Throwable $e) {
    $highlight_user = null;
  }
  if (!$highlight_user && preg_match(PlexUser::UUID_REGEX, $highlight_id) === 1) {
    $highlight_name = $highlight_id;
  } else if ($highlight_user) {
    $highlight_user_email = $highlight_user->getPlexEmail();
    $highlight_user_title = $highlight_user->getPlexTitle();
    $highlight_user_name = $highlight_user->getPlexUsername();
    $highlight_name = \sprintf('%s (%s)',
      (!empty($highlight_user_title) ? $highlight_user_title : $highlight_user_name),
      $highlight_user_email
    );
  }
}
if ($highlight_act === null) $highlight_act = '';
switch (\strtolower($highlight_act) ?? '') {
  case 'add': $highlight_act = 'added'; break;
  case 'edit': $highlight_act = 'edited'; break;
  case 'delete': $highlight_act = 'deleted'; break;
}
$title = 'Plex Users';
require('./header.inc.phtml'); ?>
<div class="container-fluid" style="max-width:1920px;">
<?php if ($this->getContext()->users === false) { ?>
  <h1><?=$title;?></h1>
  <?php require('./LoginRequired.inc.phtml'); ?>
<?php } else { ?>
<?php if (!empty($highlight_name) && !empty($highlight_act)) { ?>
  <div class="alert alert-info">
    The Plex user <strong><?=$highlight_name?></strong> was <?=$highlight_act?>.
  </div>
<?php } ?>
  <div class="float-right">
    <span class="mr-2" style="font-size:smaller;">Hidden Users:
<?php if (!$show_hidden) { ?>
      <a class="btn btn-sm btn-secondary" href="?sh=1">Show</a>
<?php } else { ?>
      <a class="btn btn-sm btn-secondary" href="?sh=0">Re-Hide</a>
<?php } ?>
    </span>
    <a class="btn btn-lg btn-success" href="<?=Common::relativeUrlToAbsolute('/plex/users/add')?>">Add User</a>
  </div>
  <h1><a href="<?=Common::relativeUrlToAbsolute('/plex/users')?>"><?=$title;?></a></h1>
  <p>The following is a list of the registered Plex users and associated data.</p>
  <table id="plex_users" class="nowrap table table-hover table-striped w-100">
    <thead class="thead-dark"><tr>
      <th scope="col">Title, Username, &amp; Email</th>
      <th scope="col">Added</th>
      <th scope="col">Tags</th>
      <th scope="col">Notes</th>
      <th scope="col"></th>
    </tr></thead>
    <tbody>
<?php foreach ($this->getContext()->users as $user) {
        if ($user->isHidden() && !$show_hidden) continue;
        $avatar = filter_var($user->getAvatar(40), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $date_added = array($user->getDateAdded()->format('D, M jS, Y'), $user->getDateAdded()->format('g:i A T'));
        $id = filter_var($user->getId(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $notes = filter_var($user->getNotes(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $plex_email = filter_var($user->getPlexEmail(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $plex_title = filter_var($user->getPlexTitle(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $plex_username = filter_var($user->getPlexUsername(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $disabled = ($user->isDisabled() ? ' <span class="badge badge-danger">Disabled</span> ' : '');
        $expired = ($user->isExpired() ? ' <span class="badge badge-warning">Expired</span> ' : '');
        $homeuser = ($user->isHomeUser() ? ' <span class="badge badge-info">Home User</span> ' : '');
        $risk = $user->getRisk();
        $name = (!empty($plex_title) ? $plex_title : (!empty($plex_username) ? $plex_username : $plex_email));
        if ($name != $plex_email && !empty($plex_email)) { $name .= sprintf('<br/><span class="text-secondary">%s</span>', $plex_email); }
        if (empty($notes)) { $notes = '<em>&ndash;</em>'; }
        switch ($risk) {
          case PlexUser::RISK_UNASSESSED: $risk = array('secondary', 'Unassessed'); break;
          case PlexUser::RISK_LOW: $risk = array('success', 'Low'); break;
          case PlexUser::RISK_MEDIUM: $risk = array('warning', 'Medium'); break;
          case PlexUser::RISK_HIGH: $risk = array('danger', 'High'); break;
          default: $risk = array('info', sprintf('Unknown (%d)', $risk));
        }
        $risk = sprintf(' <span class="badge badge-%s">%s Risk</span> ', $risk[0], $risk[1]);
        ?>
      <tr>
        <td class="align-middle">
          <div class="d-table-cell align-middle"><img class="rounded mr-2" style="height:40px;width:40px;" src="<?=$avatar?>"/></div>
          <div class="d-table-cell align-middle"><?=$name?></div>
        </td>
        <td class="align-middle"><time datetime="<?=$user->getDateAdded()->format(DATE_W3C)?>"><?=$date_added[0]?><br/><span class="text-secondary"><?=$date_added[1]?></span></time></td>
        <td class="align-middle text-center"><?=$risk?><?=$disabled?><?=$expired?><?=$homeuser?></td>
        <td class="align-middle"><?=$notes?></td>
        <td class="align-middle text-right"><a class="btn btn-sm btn-primary" href="<?=Common::relativeUrlToAbsolute('/plex/users/edit?id=' . $id)?>">Edit</a></td>
      </tr>
<?php } ?>
    </tbody>
  </table>
<?php ob_start(); ?>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#plex_users').DataTable({
        "columnDefs": [
          { responsivePriority: 1, targets: 0 },
          { responsivePriority: 3, targets: 1 },
          { responsivePriority: 2, targets: 2 },
          { responsivePriority: 4, targets: 3 },
          { responsivePriority: 1, targets: 4 }
        ],
        "columns": [
          null,
          null,
          null,
          null,
          { "orderable": false }
        ],
        "responsive": true
      });
    });
  </script>
<?php $_footer_script = ob_get_clean(); ?>
<?php } ?>
</div>
<?php require('./footer.inc.phtml'); ?>
