<?php
namespace CarlBennett\Tools\Templates\Plex\Users;
$title = 'Add Plex User';
$active_user = $this->getContext()->active_user;
$plex_user = $this->getContext()->plex_user;
require('./header.inc.phtml');
?>
<div class="container">
  <h1><?=$title;?></h1>
<?php
if (!$active_user) {
  require('./LoginRequired.inc.phtml');
} else {
  require('./Plex/Users/UserForm.inc.phtml');
}
?>
</div>
<?php require('./footer.inc.phtml');
