<?php
  namespace CarlBennett\Tools\Templates;
  use \CarlBennett\Tools\Libraries\Plex\User as PlexUser;
  use \CarlBennett\Tools\Models\Plex\Users\UserForm;

  $date_added = $plex_user->getDateAdded();
  $date_removed = $plex_user->getDateRemoved();
  $email = filter_var($this->getContext()->email, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
  $id = $this->getContext()->id;
  $notes = filter_var($this->getContext()->notes, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
  $risk = $this->getContext()->risk;
  $username = filter_var($this->getContext()->username, FILTER_SANITIZE_FULL_SPECIAL_CHARS);

  $fmt = 'D, M j, Y g:i A T';

  $date_added = (!is_null($date_added) ? $date_added->format($fmt) : '<em>(not added)</em>');
  $date_removed = (!is_null($date_removed) ? $date_removed->format($fmt) : '<em>(not removed)</em>');

  $date_added = str_replace('12:00 AM UTC', '', $date_added);
  $date_removed = str_replace('12:00 AM UTC', '', $date_removed);

  $error = $this->getContext()->error;
  switch ($error) {
    case UserForm::ERROR_SUCCESS:
      $error = ''; break;
    case UserForm::ERROR_INTERNAL_ERROR:
      $error = 'An internal error occurred while processing the request.'; break;
    case UserForm::ERROR_NULL_PLEX_USER:
      $error = 'The Plex user was null during processing of the request.'; break;
    case UserForm::ERROR_EMPTY_USERNAME_AND_EMAIL:
      $error = 'The <strong>username</strong> and <strong>email address</strong> cannot both be empty.'; break;
    case UserForm::ERROR_INVALID_RISK:
      $error = 'The selected risk option is invalid, choose a proper risk value.'; break;
  }
?>
<?php if (!empty($error)) { ?>
  <div class="alert alert-danger"><?=$error?></div>
<?php } ?>
  <form method="POST">
    <table class="table table-borderless table-hover">
      <thead></thead><tbody>
        <tr>
          <th scope="row" class="align-middle text-right"><label class="m-0" for="username">Username</label></th>
          <td><input class="form-control form-control-sm" type="text" id="username" name="username" placeholder="Enter the username here" value="<?=$username?>"/></td>
        </tr>
        <tr>
          <th scope="row" class="align-middle text-right"><label class="m-0" for="email">Email address</label></th>
          <td><input class="form-control form-control-sm" type="email" id="email" name="email" placeholder="Enter the email address here" value="<?=$email?>"/></td>
        </tr>
        <tr>
          <th scope="row" class="align-middle text-right"><label class="m-0" for="risk">Risk</label></th>
          <td>
            <select class="form-control form-control-sm" id="risk" name="risk">
              <option value="<?=PlexUser::RISK_UNASSESSED?>"<?=($risk === PlexUser::RISK_UNASSESSED ? ' selected' : '')?> class="bg-danger text-dark">Unassessed</option>
              <option value="<?=PlexUser::RISK_LOW?>"<?=($risk === PlexUser::RISK_LOW ? ' selected' : '')?> class="bg-success text-dark">Low</option>
              <option value="<?=PlexUser::RISK_MEDIUM?>"<?=($risk === PlexUser::RISK_MEDIUM ? ' selected' : '')?> class="bg-warning text-dark">Medium</option>
              <option value="<?=PlexUser::RISK_HIGH?>"<?=($risk === PlexUser::RISK_HIGH ? ' selected' : '')?> class="bg-danger text-dark">High</option>
            </select>
          </td>
        </tr>
        <tr>
          <th scope="row" class="align-top text-right"><label class="m-0" for="notes">Notes</label></th>
          <td><textarea class="form-control form-control-sm" style="min-height:90px;" id="notes" name="notes" placeholder="Enter notes here"><?=$notes?></textarea></td>
        </tr>
        <tr>
          <th scope="row" class="align-middle text-right">Date Added</th>
          <td><?=$date_added?></td>
        </tr>
        <tr>
          <th scope="row" class="align-middle text-right">Date Removed</th>
          <td><?=$date_removed?></td>
        </tr>
      </tbody>
    </table>
    <div class="text-center">
      <a class="btn btn-primary mr-2" href="javascript:history.go(-1);">Back</a>
<?php if (empty($id)) { ?>
      <input class="btn btn-success" type="submit" name="action" value="Add"/>
<?php } else { ?>
      <input class="btn btn-danger" type="submit" name="action" value="Delete"/>
      <input class="btn btn-success" type="submit" name="action" value="Save"/>
<?php } ?>
    </div>
  </form>
