<?php
namespace CarlBennett\Tools\Templates;
use \CarlBennett\MVC\Libraries\Gravatar;
use \CarlBennett\Tools\Libraries\Plex\User as PlexUser;
use \CarlBennett\Tools\Libraries\User;
use \CarlBennett\Tools\Models\Plex\Users\UserForm;
use \DateTimeZone;

$users = User::getAll();

$avatar = filter_var((new Gravatar($plex_user->getPlexEmail()))->getUrl(128, 'mp'), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$date_added = $plex_user->getDateAdded();
$date_disabled = $plex_user->getDateDisabled();
$date_expired = $plex_user->getDateExpired();
$id = $this->getContext()->id;
$is_disabled = ($this->getContext()->disabled ? ' checked' : '');
$is_expired = ($this->getContext()->expired ? ' checked' : '');
$is_hidden = ($this->getContext()->hidden ? ' checked' : '');
$is_homeuser = ($this->getContext()->homeuser ? ' checked' : '');
$notes = filter_var($this->getContext()->notes, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$plex_email = filter_var($this->getContext()->plex_email, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$plex_username = filter_var($this->getContext()->plex_username, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$record_updated = $plex_user->getRecordUpdated();
$risk = $this->getContext()->risk;
$user_id = $this->getContext()->user_id;

$fmt = 'D, M j, Y g:i A T';
$tz = ($active_user ? $active_user->getTimezoneObject() : new DateTimeZone('Etc/UTC'));

if ($date_added) $date_added->setTimezone($tz);
if ($date_disabled) $date_disabled->setTimezone($tz);
if ($date_expired) $date_expired->setTimezone($tz);
if ($record_updated) $record_updated->setTimezone($tz);

$id_str = (!is_null($id) ? $id : '<em>&ndash;</em>');
$date_added_str = (!is_null($date_added) ? $date_added->format($fmt) : '<em>(not added)</em>');
$date_disabled_str = (!is_null($date_disabled) ? $date_disabled->format($fmt) : '<em>(not disabled)</em>');
$date_expired_str = (!is_null($date_expired) ? $date_expired->format($fmt) : '<em>(not expired)</em>');
$record_updated_str = (!is_null($record_updated) ? $record_updated->format($fmt) : '<em>&ndash;</em>');

$date_disabled_class = (!is_null($date_disabled) ? 'text-danger' : 'text-secondary');
$date_expired_class = (!is_null($date_expired) ? 'text-warning' : 'text-secondary');

$error = $this->getContext()->error;
switch ($error) {
  case UserForm::ERROR_SUCCESS:
    $error = ''; break;
  case UserForm::ERROR_INTERNAL_ERROR:
    $error = 'An internal error occurred while processing the request.'; break;
  case UserForm::ERROR_NULL_PLEX_USER:
    $error = 'The Plex user was null during processing of the request.'; break;
  case UserForm::ERROR_EMPTY_USERNAME_AND_EMAIL:
    $error = 'The <strong>username</strong> and <strong>email address</strong> cannot both be empty.'; break;
  case UserForm::ERROR_INVALID_RISK:
    $error = 'The selected risk option is invalid, choose a proper risk value.'; break;
  case UserForm::ERROR_LINKED_USER_ALREADY_ASSIGNED:
    $error = 'That user is already linked to another Plex user.'; break;
}

if (!empty($error)) { ?>
  <div class="alert alert-danger"><?=$error?></div>
<?php } ?>
  <form method="POST">
    <div class="row">
      <div class="col-md-1">
        <!-- Avatar -->

        <div class="text-center">
          <label class="font-weight-bold m-1">Gravatar</label>
          <img class="border border-primary p-1 rounded-lg" style="max-width:128px;" src="<?=$avatar?>"/>
        </div>

      </div>
      <div class="col-lg-6">
        <!-- Username, Email address, Linked user, Risk, Options -->

        <table class="table table-borderless">
          <thead></thead><tbody>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="plex_username">Username</label></th>
              <td><input class="form-control form-control-sm" type="text" id="plex_username" name="plex_username" placeholder="Enter the Plex username here" value="<?=$plex_username?>"/></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="plex_email">Email address</label></th>
              <td><input class="form-control form-control-sm" type="email" id="plex_email" name="plex_email" placeholder="Enter the Plex email address here" value="<?=$plex_email?>"/></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="user_id">Linked user</label></th>
              <td>
                <select class="custom-select custom-select-sm" id="user_id" name="user_id">
                  <option value=""<?=(!$user_id ? ' selected' : '')?>>&ndash;</option>
<?php foreach ($users as $user) { ?>
                  <option value="<?=$user->getId()?>"<?=($user_id == $user->getId() ? ' selected' : '')?>><?=filter_var($user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></option>
<?php } ?>
                </select>
              </td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0" for="risk">Risk</label></th>
              <td>
                <select class="custom-select custom-select-sm" id="risk" name="risk">
                  <option value="<?=PlexUser::RISK_UNASSESSED?>"<?=($risk === PlexUser::RISK_UNASSESSED ? ' selected' : '')?> class="bg-secondary text-dark">Unassessed</option>
                  <option value="<?=PlexUser::RISK_LOW?>"<?=($risk === PlexUser::RISK_LOW ? ' selected' : '')?> class="bg-success text-dark">Low</option>
                  <option value="<?=PlexUser::RISK_MEDIUM?>"<?=($risk === PlexUser::RISK_MEDIUM ? ' selected' : '')?> class="bg-warning text-dark">Medium</option>
                  <option value="<?=PlexUser::RISK_HIGH?>"<?=($risk === PlexUser::RISK_HIGH ? ' selected' : '')?> class="bg-danger text-dark">High</option>
                </select>
              </td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right"><label class="m-0">Options</label></th>
              <td>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="disabled" id="is_disabled" value="1"<?=$is_disabled?>> <label class="custom-control-label" for="is_disabled">Disabled</label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="expired" id="is_expired" value="1"<?=$is_expired?>> <label class="custom-control-label" for="is_expired">Expired</label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="hidden" id="is_hidden" value="1"<?=$is_hidden?>> <label class="custom-control-label" for="is_hidden">Hidden</label>
                </div>
                <div class="custom-control custom-switch m-2">
                  <input class="custom-control-input" type="checkbox" name="homeuser" id="is_homeuser" value="1"<?=$is_homeuser?>> <label class="custom-control-label" for="is_homeuser">Home User</label>
                </div>
              </td>
            </tr>
          </tbody>
        </table>

      </div>
      <div class="col-lg-5">
        <!-- Uuid, Timestamps -->

        <table class="table table-borderless">
          <thead></thead><tbody>
            <tr>
              <th scope="row" class="align-middle text-right">Uuid</th>
              <td><code><?=$id_str?></code></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right text-success">Date added</th>
              <td class="text-success"><?=$date_added_str?></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right <?=$date_expired_class?>">Date expired</th>
              <td class="<?=$date_expired_class?>"><?=$date_expired_str?></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right <?=$date_disabled_class?>">Date disabled</th>
              <td class="<?=$date_disabled_class?>"><?=$date_disabled_str?></td>
            </tr>
            <tr>
              <th scope="row" class="align-middle text-right text-info">Record last updated</th>
              <td class="text-info"><?=$record_updated_str?></td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
    <div class="row">
      <div class="col">
        <!-- Notes -->

        <label class="font-weight-bold" for="notes">Notes</label><br/>
        <textarea class="form-control form-control-sm" style="min-height:90px;" id="notes" name="notes" placeholder="Enter notes here"><?=$notes?></textarea>

      </div>
    </div>
    <hr/>
    <div class="row">
      <div class="col">
        <div class="text-center">
          <a class="btn btn-primary mr-2" href="javascript:history.go(-1);">Back</a>
<?php if (empty($id)) { ?>
          <input class="btn btn-success" type="submit" value="Add"/>
<?php } else { ?>
          <input class="btn btn-success" type="submit" value="Save"/>
<?php } ?>
        </div>
      </div>
    </div>
  </form>
